### ISSUE TITLE
Friends Page

### ISSUE THREAD

**Issue by varmendari14** [kscharm/digital-time-capsule#19]
Create a page for users to view their friends (and add and remove friends).

**Comment by stephaniebaione** [comment]
##Story/Task Details
-[ ] Create the Base page for personal time capsule.
-[ ] Create an add button.
-[ ] Create a top bar.

#Acceptance Scenarios
Given: The presence of an add button on the personal page
When: the user clicks on the add button
Then: a pop up with icons representing the items a user can add should appear.

Given: The presence of top bar icons
When: the user clicks on an icon
Then: the appropriate menu should drop down.
